version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - Katyara11

  - package-ecosystem: terraform
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - Katyara11
